[package]
name = "raesan-dataset"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
clap = { version = "4.5.19", features = ["derive"] }
mime_guess = "2.0.5"
serde = { version = "1.0.170", features = ["derive"] }
serde_json = "1.0.84"
uuid = { version = "1.10.0", features = ["v4"]}
